/**
 * Cross-implementation parity: replay the exact inputs recorded from
 * Python auditok (tests/fixtures/parity.json, generated by
 * tools/generate_fixtures.py) through the JS port and require the same
 * outputs — same tokens from the tokenizer, same events from split,
 * same estimated thresholds.
 */

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

import {
  computeFrameEnergies,
  decodeWav,
  estimateEnergyThreshold,
  splitAll,
  StreamTokenizer,
  type SplitOptions,
  type ThresholdMethod,
} from "../src/index.js";

const fixturesDir = fileURLToPath(new URL("fixtures/", import.meta.url));

interface TokenizerCase {
  params: {
    min_length: number;
    max_length: number | null;
    max_continuous_silence: number;
    max_leading_silence?: number;
    max_trailing_silence?: number;
    init_min?: number;
    init_max_silence?: number;
    mode?: number;
  };
  input: string;
  tokens: { data: string; start: number; end: number }[];
}

interface SplitCase {
  file: string;
  options: Record<string, unknown>;
  events: { start: number; end: number }[];
}

interface ThresholdCase {
  file: string;
  method: ThresholdMethod;
  percentile?: number;
  threshold: number;
}

const parity = JSON.parse(
  readFileSync(`${fixturesDir}parity.json`, "utf8"),
) as {
  auditok_version: string;
  tokenizer_cases: TokenizerCase[];
  split_cases: SplitCase[];
  threshold_cases: ThresholdCase[];
};

const wavCache = new Map<string, ReturnType<typeof decodeWav>>();

function loadFixtureWav(name: string) {
  let decoded = wavCache.get(name);
  if (decoded === undefined) {
    decoded = decodeWav(readFileSync(`${fixturesDir}${name}`));
    wavCache.set(name, decoded);
  }
  return decoded;
}

function toSplitOptions(options: Record<string, unknown>): SplitOptions {
  const renamed: Record<string, string> = {
    energy_threshold: "energyThreshold",
    min_dur: "minDur",
    max_dur: "maxDur",
    max_silence: "maxSilence",
    max_leading_silence: "maxLeadingSilence",
    max_trailing_silence: "maxTrailingSilence",
    use_channel: "useChannel",
    validator: "validator",
  };
  const result: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(options)) {
    const jsName = renamed[key];
    if (jsName === undefined) {
      throw new Error(`unmapped Python option '${key}'`);
    }
    result[jsName] = value;
  }
  return result as SplitOptions;
}

describe("StreamTokenizer parity with Python auditok", () => {
  const isUpper = (c: string) => c >= "A" && c <= "Z";

  it.each(
    parity.tokenizer_cases.map((c, i) => [i, c] as const),
  )("case %i", async (_i, testCase) => {
    const p = testCase.params;
    const tokenizer = new StreamTokenizer<string>(isUpper, {
      minLength: p.min_length,
      maxLength: p.max_length ?? Infinity,
      maxContinuousSilence: p.max_continuous_silence,
      maxLeadingSilence: p.max_leading_silence ?? 0,
      maxTrailingSilence: p.max_trailing_silence ?? null,
      strictMinLength: ((p.mode ?? 0) & 2) !== 0,
      initMin: p.init_min ?? 0,
      initMaxSilence: p.init_max_silence ?? 0,
    });
    const tokens = await tokenizer.tokenizeAll(testCase.input);
    expect(
      tokens.map((t) => ({
        data: t.frames.join(""),
        start: t.start,
        end: t.end,
      })),
    ).toEqual(testCase.tokens);
  });
});

describe("split parity with Python auditok", () => {
  it.each(
    parity.split_cases.map(
      (c, i) => [i, c.file, JSON.stringify(c.options), c] as const,
    ),
  )("case %i: %s %s", async (_i, file, _opts, testCase) => {
    const audio = loadFixtureWav(file);
    const events = await splitAll(audio, toSplitOptions(testCase.options));
    expect(events.length).toBe(testCase.events.length);
    events.forEach((event, k) => {
      expect(event.start).toBeCloseTo(testCase.events[k].start, 9);
      expect(event.end).toBeCloseTo(testCase.events[k].end, 9);
    });
  });
});

describe("threshold estimation parity with Python auditok", () => {
  it.each(
    parity.threshold_cases.map((c, i) => [i, c.file, c.method, c] as const),
  )("case %i: %s %s", (_i, file, method, testCase) => {
    const audio = loadFixtureWav(file);
    const frameSamples = Math.round(0.05 * audio.sampleRate);
    const energies = computeFrameEnergies(audio.channelData, frameSamples);
    const threshold = estimateEnergyThreshold(
      energies,
      method,
      testCase.percentile === undefined
        ? {}
        : { percentile: testCase.percentile },
    );
    expect(threshold).toBeCloseTo(testCase.threshold, 6);
  });
});
